#ifndef MODBUS_H_
#define MODBUS_H_

//coil register addressing
#define REQUESTTOSTARTCALIBRATION 1
#define REQUESTTOSTARTZEROTEST 2
#define REQUESTTOSTARTMEASURMENTOFELEMENTALMERCURY 3
#define REQUESTTOSTARTPURGE 4
#define REQUESTTOENDPURGE 5
#define STATUSOFSPECTROMETER 6
#define STATUSOFTHERMOCONTROLLERS 7
#define AVAILABILITYOFEXTERNALREQUEST 8
#define STATUSOFZEROTEST 9 
#define STATUSOFCALIBRATION 10

//holding register addressing
#define MONITORFLOW 11
#define VACUUM 12
#define DILUTIONPRESSURE 13
#define BYPASSPRESSURE 14
#define TEMPERATUREOFSPECTROMETER 15
#define CODEOFACURRENTMODE 16
#define ERRORSANDWARNINGS 17
#define TOTALMERCURYCOEFFICENT 18

//status word mask
#define ALLOK 0
#define NO_DATA 1
#define LOW_LIGHT 2
#define LOW_FLOW 4
#define CONVERTER 8
#define WATLOW1 16
#define WATLOW2 32
#define WATLOW3 64
#define WATLOW4 128


#endif /* MODBUS_H_ */