/*
 * settings.h
 *
 * Created: 19-Jul-16 13:44:15
 *  Author: Art Navsegda
 */ 


#ifndef SETTINGS_H_
#define SETTINGS_H_

#define CALIBRATIONCOEFFICENTA 1390 // not use
#define CALIBRATIONCOEFFICENTB 35000 // not use
#define CALIBRATIONCOEFFICENTMAX 0.05
#define CALIBRATIONCOEFFICENTMIN 0.005
#define STANDARDCONCENTRATION 2.68
#define CALIBRATIONCOEFFICENTTOTAL 0.05
#define RATIOOFHGELEMENTALHGTOTAL 1
#define HGELEMENTALBIAS 0
#define THRESHOLDFORTOTALANDELEMENTALCONCENTRATIONS 0
#define FLOWRATEMAXLPM 44
#define FLOWRATEMINLPM -80
#define PANALCELLMAXKPA 115
#define PANALCELLMINKPA 45
#define TANALCELLMAXDEGC 80
#define TANALCELLMINDEGC 0
#define TSPECMAXDEGC 70
#define TSPECMINDEGC 1
#define MINIMUMACCEPTABLEPMTIARB 1000
#define LAMPTHRESHOLD1EARLYWARNINGARB 500
#define LAMPTHRESHOLD2URGENTWARNINGARB 1000

#define VACUUMBIAS 0
#define VACUUMCALIBRATIONCOEFFICENT 0.1
#define DILUTIONPRESSUREBIAS 0
#define DILUTIONPRESSURECALIBRATIONCOEFFICENT 0.1
#define BYPASSPRESSUREBIAS 0
#define BYPASSCALIBRATIONCOEFFICENT 0.1
#define AIRPRESSURESENSORBIAS 0
#define AIRPRESSURESENSORCALIBRATIONCOEFFICENT 0.01

#define AIRTEMPERATURESENSORCALIBRATIONCOEFFICENT 1
#define CELLTEMPERATURESENSORCALIBARATIONCOEFFICENT 0,97

#define FLOWRATEBIAS 635
#define FLOWRATECALIBRATIONCOEFFICIENT 0.0055

#define DARKCURRENTPMT 39
#define PROTOCOLNUMBER 0

#define COILREADREGISTERFORREADINESSFOREXTERNALREQUEST 3
#define COILREADREGISTERFORSTATUSOFZEROTEST 4
#define COILREADREGISTERFORSTATUSOFCALIBRATION 5

#define FLOATREGISTERFORELEMENTALMERCURY 25
#define FLOATREGISTERFORTOTALMERCURY 11
#define FLOATREGISTERFOROXIDIZEDMERCURY 13
#define FLOATREGISTERFORMODE 9
#define FLOATREGISTERFORANALYZERSTATUS 29
#define FLOATREGISTERFORCALIBRATIONCOEFFICIENT 31
#define FLOATREGISTERFORLAMPSTATUS 35

#define COILWRITEREGISTERFOREXTERNALCALIBRATIONREQUEST 100
#define COILWRITEREGISTERFOREXTERNALELEMENTALREQUEST 102
#define COILWRITEREGISTERFOREXTERNALZEROREQUEST 101
#define COILWRITEREGISTERFORSTARTPURGECYCLE 103
#define COILWRITEREGISTERFORENDPURGECYCLE 104

#define SPECTROMETERSERIAL 86
#define PLANTLOCATION "Demo in Texas"
#define UNITNUMBER 1
#define USEELEMENTALHGMEASURMENT TRUE
#define AVERAGINGINTERVALSEC 5
#define ZERODELAYONSTARTSEC 18
#define SPECTROMENTERWARMUPTIMESEC 18
#define DEPTHOFDATASTORAGEDAYS 7
#define DURATIONPURGEMAXHOURS 10



#endif /* SETTINGS_H_ */